# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spin.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(828, 614)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("margin:0 0 0 0;\n"
"Padding:0 0 0 0;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("font: 10pt \"Arial\";")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_2.addWidget(self.checkBox_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter_2 = QtWidgets.QSplitter(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setMinimumSize(QtCore.QSize(0, 0))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setHandleWidth(5)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(0, 50))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(6)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.source_edit = QtWidgets.QPlainTextEdit(self.splitter)
        self.source_edit.setStyleSheet("font: 10pt \"Arial\";")
        self.source_edit.setPlainText("")
        self.source_edit.setObjectName("source_edit")
        self.pml_edit = QtWidgets.QPlainTextEdit(self.splitter)
        self.pml_edit.setStyleSheet("font: 10pt \"Arial\";\n"
"")
        self.pml_edit.setPlainText("")
        self.pml_edit.setObjectName("pml_edit")
        self.report_edit = QtWidgets.QPlainTextEdit(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.report_edit.sizePolicy().hasHeightForWidth())
        self.report_edit.setSizePolicy(sizePolicy)
        self.report_edit.setMinimumSize(QtCore.QSize(0, 0))
        self.report_edit.setStyleSheet("background-color: rgb(12, 12, 12);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"Bahnschrift\";\n"
"font: 87 9pt \"Arial Black\";\n"
"font: 25 9pt \"Bahnschrift Light\";")
        self.report_edit.setReadOnly(True)
        self.report_edit.setPlainText("")
        self.report_edit.setObjectName("report_edit")
        self.verticalLayout_4.addWidget(self.splitter_2)
        self.verticalLayout_3.addWidget(self.widget_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 828, 26))
        self.menubar.setObjectName("menubar")
        self.menu_protocol = QtWidgets.QMenu(self.menubar)
        self.menu_protocol.setObjectName("menu_protocol")
        self.menu_2 = QtWidgets.QMenu(self.menu_protocol)
        self.menu_2.setObjectName("menu_2")
        self.menuWEP = QtWidgets.QMenu(self.menu_2)
        self.menuWEP.setObjectName("menuWEP")
        self.menuSTP = QtWidgets.QMenu(self.menu_2)
        self.menuSTP.setObjectName("menuSTP")
        self.menu_3 = QtWidgets.QMenu(self.menu_protocol)
        self.menu_3.setObjectName("menu_3")
        self.menuUDP = QtWidgets.QMenu(self.menu_3)
        self.menuUDP.setObjectName("menuUDP")
        self.menu_4 = QtWidgets.QMenu(self.menu_protocol)
        self.menu_4.setObjectName("menu_4")
        self.menuBGP = QtWidgets.QMenu(self.menu_4)
        self.menuBGP.setObjectName("menuBGP")
        self.menuOSPF = QtWidgets.QMenu(self.menu_4)
        self.menuOSPF.setObjectName("menuOSPF")
        self.menuNDP = QtWidgets.QMenu(self.menu_4)
        self.menuNDP.setObjectName("menuNDP")
        self.menu_5 = QtWidgets.QMenu(self.menu_protocol)
        self.menu_5.setObjectName("menu_5")
        self.menuTFTP = QtWidgets.QMenu(self.menu_5)
        self.menuTFTP.setObjectName("menuTFTP")
        self.menuFTP = QtWidgets.QMenu(self.menu_5)
        self.menuFTP.setObjectName("menuFTP")
        self.menu_verti = QtWidgets.QMenu(self.menubar)
        self.menu_verti.setObjectName("menu_verti")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menubar)
        self.actionIEEE802 = QtWidgets.QAction(MainWindow)
        self.actionIEEE802.setObjectName("actionIEEE802")
        self.actionIEEE802W = QtWidgets.QAction(MainWindow)
        self.actionIEEE802W.setObjectName("actionIEEE802W")
        self.actionWEP_MITM = QtWidgets.QAction(MainWindow)
        self.actionWEP_MITM.setObjectName("actionWEP_MITM")
        self.actionWEP_none = QtWidgets.QAction(MainWindow)
        self.actionWEP_none.setObjectName("actionWEP_none")
        self.actionSTP_MI = QtWidgets.QAction(MainWindow)
        self.actionSTP_MI.setObjectName("actionSTP_MI")
        self.actionSTP_MITM = QtWidgets.QAction(MainWindow)
        self.actionSTP_MITM.setObjectName("actionSTP_MITM")
        self.actionSTP_none = QtWidgets.QAction(MainWindow)
        self.actionSTP_none.setObjectName("actionSTP_none")
        self.actionSSL3_0 = QtWidgets.QAction(MainWindow)
        self.actionSSL3_0.setObjectName("actionSSL3_0")
        self.actionTLS = QtWidgets.QAction(MainWindow)
        self.actionTLS.setObjectName("actionTLS")
        self.actionUDP_dos = QtWidgets.QAction(MainWindow)
        self.actionUDP_dos.setObjectName("actionUDP_dos")
        self.actionUDP_none = QtWidgets.QAction(MainWindow)
        self.actionUDP_none.setObjectName("actionUDP_none")
        self.actionqi = QtWidgets.QAction(MainWindow)
        self.actionqi.setObjectName("actionqi")
        self.actionIKEV2 = QtWidgets.QAction(MainWindow)
        self.actionIKEV2.setObjectName("actionIKEV2")
        self.actionBDP_MI = QtWidgets.QAction(MainWindow)
        self.actionBDP_MI.setObjectName("actionBDP_MI")
        self.actionBGP_MITI = QtWidgets.QAction(MainWindow)
        self.actionBGP_MITI.setObjectName("actionBGP_MITI")
        self.actionBGP_none = QtWidgets.QAction(MainWindow)
        self.actionBGP_none.setObjectName("actionBGP_none")
        self.actionOSPF_MI = QtWidgets.QAction(MainWindow)
        self.actionOSPF_MI.setObjectName("actionOSPF_MI")
        self.actionOSPF_none = QtWidgets.QAction(MainWindow)
        self.actionOSPF_none.setObjectName("actionOSPF_none")
        self.actionNDP_mac = QtWidgets.QAction(MainWindow)
        self.actionNDP_mac.setObjectName("actionNDP_mac")
        self.actionNDP_MAC = QtWidgets.QAction(MainWindow)
        self.actionNDP_MAC.setObjectName("actionNDP_MAC")
        self.actionNDP_none = QtWidgets.QAction(MainWindow)
        self.actionNDP_none.setObjectName("actionNDP_none")
        self.actionNDP_pix = QtWidgets.QAction(MainWindow)
        self.actionNDP_pix.setObjectName("actionNDP_pix")
        self.actionSNMP = QtWidgets.QAction(MainWindow)
        self.actionSNMP.setObjectName("actionSNMP")
        self.actionkioboler = QtWidgets.QAction(MainWindow)
        self.actionkioboler.setObjectName("actionkioboler")
        self.actionRPC = QtWidgets.QAction(MainWindow)
        self.actionRPC.setObjectName("actionRPC")
        self.actionRPC_therom = QtWidgets.QAction(MainWindow)
        self.actionRPC_therom.setObjectName("actionRPC_therom")
        self.actionTFTP_MI = QtWidgets.QAction(MainWindow)
        self.actionTFTP_MI.setObjectName("actionTFTP_MI")
        self.actionTFTP_none = QtWidgets.QAction(MainWindow)
        self.actionTFTP_none.setObjectName("actionTFTP_none")
        self.actionFTP_attack = QtWidgets.QAction(MainWindow)
        self.actionFTP_attack.setObjectName("actionFTP_attack")
        self.actionFTP_none = QtWidgets.QAction(MainWindow)
        self.actionFTP_none.setObjectName("actionFTP_none")
        self.atcionConver = QtWidgets.QAction(MainWindow)
        self.atcionConver.setObjectName("atcionConver")
        self.actionRun = QtWidgets.QAction(MainWindow)
        self.actionRun.setObjectName("actionRun")
        self.actionReport = QtWidgets.QAction(MainWindow)
        self.actionReport.setObjectName("actionReport")
        self.actionReportChart = QtWidgets.QAction(MainWindow)
        self.actionReportChart.setObjectName("actionReportChart")
        self.actionCheckSpin = QtWidgets.QAction(MainWindow)
        self.actionCheckSpin.setObjectName("actionCheckSpin")
        self.actionAutoInstall = QtWidgets.QAction(MainWindow)
        self.actionAutoInstall.setObjectName("actionAutoInstall")
        self.actionnscode = QtWidgets.QAction(MainWindow)
        self.actionnscode.setObjectName("actionnscode")
        self.new_2 = QtWidgets.QAction(MainWindow)
        self.new_2.setObjectName("new_2")
        self.new_protocol = QtWidgets.QAction(MainWindow)
        self.new_protocol.setObjectName("new_protocol")
        self.version_action = QtWidgets.QAction(MainWindow)
        self.version_action.setObjectName("version_action")
        self.toolBar.addAction(self.atcionConver)
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addAction(self.actionReport)
        self.toolBar.addAction(self.actionReportChart)
        self.menuWEP.addAction(self.actionWEP_MITM)
        self.menuWEP.addAction(self.actionWEP_none)
        self.menuSTP.addAction(self.actionSTP_MI)
        self.menuSTP.addAction(self.actionSTP_MITM)
        self.menuSTP.addAction(self.actionSTP_none)
        self.menu_2.addAction(self.actionIEEE802)
        self.menu_2.addAction(self.actionIEEE802W)
        self.menu_2.addAction(self.menuWEP.menuAction())
        self.menu_2.addAction(self.menuSTP.menuAction())
        self.menu_2.addAction(self.actionqi)
        self.menu_2.addAction(self.actionnscode)
        self.menuUDP.addAction(self.actionUDP_dos)
        self.menuUDP.addAction(self.actionUDP_none)
        self.menu_3.addAction(self.actionSSL3_0)
        self.menu_3.addAction(self.actionTLS)
        self.menu_3.addAction(self.menuUDP.menuAction())
        self.menuBGP.addAction(self.actionBDP_MI)
        self.menuBGP.addAction(self.actionBGP_MITI)
        self.menuBGP.addAction(self.actionBGP_none)
        self.menuOSPF.addAction(self.actionOSPF_MI)
        self.menuOSPF.addAction(self.actionOSPF_none)
        self.menuNDP.addAction(self.actionNDP_mac)
        self.menuNDP.addAction(self.actionNDP_MAC)
        self.menuNDP.addAction(self.actionNDP_none)
        self.menuNDP.addAction(self.actionNDP_pix)
        self.menu_4.addAction(self.actionIKEV2)
        self.menu_4.addAction(self.menuBGP.menuAction())
        self.menu_4.addAction(self.menuOSPF.menuAction())
        self.menu_4.addAction(self.menuNDP.menuAction())
        self.menuTFTP.addAction(self.actionTFTP_MI)
        self.menuTFTP.addAction(self.actionTFTP_none)
        self.menuFTP.addAction(self.actionFTP_attack)
        self.menuFTP.addAction(self.actionFTP_none)
        self.menu_5.addAction(self.actionSNMP)
        self.menu_5.addAction(self.actionkioboler)
        self.menu_5.addAction(self.actionRPC)
        self.menu_5.addAction(self.actionRPC_therom)
        self.menu_5.addAction(self.menuTFTP.menuAction())
        self.menu_5.addAction(self.menuFTP.menuAction())
        self.menu_protocol.addAction(self.menu_2.menuAction())
        self.menu_protocol.addAction(self.menu_3.menuAction())
        self.menu_protocol.addAction(self.menu_4.menuAction())
        self.menu_protocol.addAction(self.menu_5.menuAction())
        self.menu_protocol.addAction(self.new_protocol)
        self.menu_verti.addAction(self.atcionConver)
        self.menu_verti.addAction(self.actionRun)
        self.menu_verti.addAction(self.actionReport)
        self.menu_verti.addAction(self.actionReportChart)
        self.menu_help.addAction(self.actionCheckSpin)
        self.menu_help.addAction(self.actionAutoInstall)
        self.menu_help.addAction(self.version_action)
        self.menubar.addAction(self.menu_protocol.menuAction())
        self.menubar.addAction(self.menu_verti.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "网络设备与协议安全性分析工具-协议形式化分析"))
        self.label.setText(_translate("MainWindow", "max depth N steps"))
        self.label_2.setText(_translate("MainWindow", "stop at Nth error"))
        self.lineEdit.setText(_translate("MainWindow", "1"))
        self.lineEdit_2.setText(_translate("MainWindow", "1000"))
        self.checkBox.setText(_translate("MainWindow", "print all statment"))
        self.checkBox_2.setText(_translate("MainWindow", "print local statment"))
        self.checkBox_3.setText(_translate("MainWindow", "print send statment"))
        self.checkBox_4.setText(_translate("MainWindow", "print receive statment"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menu_protocol.setTitle(_translate("MainWindow", "协议"))
        self.menu_2.setTitle(_translate("MainWindow", "链路层"))
        self.menuWEP.setTitle(_translate("MainWindow", "WEP"))
        self.menuSTP.setTitle(_translate("MainWindow", "STP"))
        self.menu_3.setTitle(_translate("MainWindow", "传输层"))
        self.menuUDP.setTitle(_translate("MainWindow", "UDP"))
        self.menu_4.setTitle(_translate("MainWindow", "网络层"))
        self.menuBGP.setTitle(_translate("MainWindow", "BGP"))
        self.menuOSPF.setTitle(_translate("MainWindow", "OSPF"))
        self.menuNDP.setTitle(_translate("MainWindow", "NDP"))
        self.menu_5.setTitle(_translate("MainWindow", "应用层"))
        self.menuTFTP.setTitle(_translate("MainWindow", "TFTP"))
        self.menuFTP.setTitle(_translate("MainWindow", "FTP"))
        self.menu_verti.setTitle(_translate("MainWindow", "验证"))
        self.menu_help.setTitle(_translate("MainWindow", "帮助"))
        self.actionIEEE802.setText(_translate("MainWindow", "IEEE80211I"))
        self.actionIEEE802W.setText(_translate("MainWindow", "IEEE80211w"))
        self.actionWEP_MITM.setText(_translate("MainWindow", "WEP_MITM"))
        self.actionWEP_none.setText(_translate("MainWindow", "WEP_none"))
        self.actionSTP_MI.setText(_translate("MainWindow", "STP_MI"))
        self.actionSTP_MITM.setText(_translate("MainWindow", "STP_MITM"))
        self.actionSTP_none.setText(_translate("MainWindow", "STP_none"))
        self.actionSSL3_0.setText(_translate("MainWindow", "SSL3.0"))
        self.actionTLS.setText(_translate("MainWindow", "TLS"))
        self.actionUDP_dos.setText(_translate("MainWindow", "UDP_dos"))
        self.actionUDP_none.setText(_translate("MainWindow", "UDP_none"))
        self.actionqi.setText(_translate("MainWindow", "其他"))
        self.actionIKEV2.setText(_translate("MainWindow", "IKEV2"))
        self.actionBDP_MI.setText(_translate("MainWindow", "BGP_MI"))
        self.actionBGP_MITI.setText(_translate("MainWindow", "BGP_MITM"))
        self.actionBGP_none.setText(_translate("MainWindow", "BGP_none"))
        self.actionOSPF_MI.setText(_translate("MainWindow", "OSPF_MI"))
        self.actionOSPF_none.setText(_translate("MainWindow", "OSPF_none"))
        self.actionNDP_mac.setText(_translate("MainWindow", "NDP_duplicate"))
        self.actionNDP_MAC.setText(_translate("MainWindow", "NDP_MAC"))
        self.actionNDP_none.setText(_translate("MainWindow", "NDP_none"))
        self.actionNDP_pix.setText(_translate("MainWindow", "NDP_prefix"))
        self.actionSNMP.setText(_translate("MainWindow", "SNMP"))
        self.actionkioboler.setText(_translate("MainWindow", "Kerberos"))
        self.actionRPC.setText(_translate("MainWindow", "RPC"))
        self.actionRPC_therom.setText(_translate("MainWindow", "RPC_theorem"))
        self.actionTFTP_MI.setText(_translate("MainWindow", "TFTP_MITM"))
        self.actionTFTP_none.setText(_translate("MainWindow", "TFTP_none"))
        self.actionFTP_attack.setText(_translate("MainWindow", "FTP_attack"))
        self.actionFTP_none.setText(_translate("MainWindow", "FTP_none"))
        self.atcionConver.setText(_translate("MainWindow", "转换"))
        self.actionRun.setText(_translate("MainWindow", "运行"))
        self.actionReport.setText(_translate("MainWindow", "报告"))
        self.actionReportChart.setText(_translate("MainWindow", "报告图"))
        self.actionCheckSpin.setText(_translate("MainWindow", "检查SPIN"))
        self.actionAutoInstall.setText(_translate("MainWindow", "自动安装"))
        self.actionnscode.setText(_translate("MainWindow", "nscode"))
        self.new_2.setText(_translate("MainWindow", "新建协议"))
        self.new_protocol.setText(_translate("MainWindow", "新建协议"))
        self.version_action.setText(_translate("MainWindow", "版本"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
