# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'songzifang.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(822, 680)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.http = QtWidgets.QPushButton(self.widget_2)
        self.http.setMaximumSize(QtCore.QSize(100, 30))
        self.http.setObjectName("http")
        self.gridLayout.addWidget(self.http, 0, 3, 1, 1)
        self.snmp = QtWidgets.QPushButton(self.widget_2)
        self.snmp.setMinimumSize(QtCore.QSize(0, 0))
        self.snmp.setMaximumSize(QtCore.QSize(100, 30))
        self.snmp.setObjectName("snmp")
        self.gridLayout.addWidget(self.snmp, 0, 1, 1, 1)
        self.all = QtWidgets.QComboBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.all.sizePolicy().hasHeightForWidth())
        self.all.setSizePolicy(sizePolicy)
        self.all.setMaximumSize(QtCore.QSize(100, 25))
        self.all.setObjectName("all")
        self.all.addItem("")
        self.all.addItem("")
        self.all.addItem("")
        self.all.addItem("")
        self.all.addItem("")
        self.all.addItem("")
        self.gridLayout.addWidget(self.all, 1, 1, 1, 1)
        self.rule = QtWidgets.QComboBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rule.sizePolicy().hasHeightForWidth())
        self.rule.setSizePolicy(sizePolicy)
        self.rule.setMaximumSize(QtCore.QSize(180, 30))
        self.rule.setObjectName("rule")
        self.rule.addItem("")
        self.rule.addItem("")
        self.rule.addItem("")
        self.gridLayout.addWidget(self.rule, 1, 3, 1, 1)
        self.dns = QtWidgets.QPushButton(self.widget_2)
        self.dns.setMaximumSize(QtCore.QSize(100, 30))
        self.dns.setObjectName("dns")
        self.gridLayout.addWidget(self.dns, 0, 4, 1, 1)
        self.ftp = QtWidgets.QPushButton(self.widget_2)
        self.ftp.setMaximumSize(QtCore.QSize(100, 30))
        self.ftp.setObjectName("ftp")
        self.gridLayout.addWidget(self.ftp, 0, 2, 1, 1)
        self.cwe_info = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cwe_info.sizePolicy().hasHeightForWidth())
        self.cwe_info.setSizePolicy(sizePolicy)
        self.cwe_info.setMaximumSize(QtCore.QSize(100, 30))
        self.cwe_info.setObjectName("cwe_info")
        self.gridLayout.addWidget(self.cwe_info, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table = QtWidgets.QTableWidget(self.widget)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.horizontalLayout.addWidget(self.table)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "渗透报文生成系统"))
        self.http.setText(_translate("Form", "http"))
        self.snmp.setText(_translate("Form", "snmp"))
        self.all.setCurrentText(_translate("Form", "漏洞"))
        self.all.setItemText(0, _translate("Form", "漏洞"))
        self.all.setItemText(1, _translate("Form", "所有漏洞"))
        self.all.setItemText(2, _translate("Form", "dlink漏洞"))
        self.all.setItemText(3, _translate("Form", "huawei漏洞"))
        self.all.setItemText(4, _translate("Form", "tenda漏洞"))
        self.all.setItemText(5, _translate("Form", "tplink漏洞"))
        self.rule.setItemText(0, _translate("Form", "关联规则"))
        self.rule.setItemText(1, _translate("Form", "网络设备关联规则"))
        self.rule.setItemText(2, _translate("Form", "漏洞类别关联规则"))
        self.dns.setText(_translate("Form", "dns"))
        self.ftp.setText(_translate("Form", "ftp"))
        self.cwe_info.setText(_translate("Form", "CWE信息"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
