# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'songzifang2.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 577)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.verticalLayout.addWidget(self.table)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 26))
        self.menubar.setObjectName("menubar")
        self.protocol_menu = QtWidgets.QMenu(self.menubar)
        self.protocol_menu.setObjectName("protocol_menu")
        self.help_menu = QtWidgets.QMenu(self.menubar)
        self.help_menu.setObjectName("help_menu")
        self.menu_vul = QtWidgets.QMenu(self.menubar)
        self.menu_vul.setObjectName("menu_vul")
        self.menuall = QtWidgets.QMenu(self.menu_vul)
        self.menuall.setObjectName("menuall")
        MainWindow.setMenuBar(self.menubar)
        self.network_menu = QtWidgets.QAction(MainWindow)
        self.network_menu.setObjectName("network_menu")
        self.trans_menu = QtWidgets.QAction(MainWindow)
        self.trans_menu.setObjectName("trans_menu")
        self.snmp_action = QtWidgets.QAction(MainWindow)
        self.snmp_action.setObjectName("snmp_action")
        self.ftp_action = QtWidgets.QAction(MainWindow)
        self.ftp_action.setObjectName("ftp_action")
        self.http_action = QtWidgets.QAction(MainWindow)
        self.http_action.setObjectName("http_action")
        self.dns_action = QtWidgets.QAction(MainWindow)
        self.dns_action.setObjectName("dns_action")
        self.other_action = QtWidgets.QAction(MainWindow)
        self.other_action.setObjectName("other_action")
        self.all_action = QtWidgets.QAction(MainWindow)
        self.all_action.setObjectName("all_action")
        self.tplink_action = QtWidgets.QAction(MainWindow)
        self.tplink_action.setObjectName("tplink_action")
        self.dlink_action = QtWidgets.QAction(MainWindow)
        self.dlink_action.setObjectName("dlink_action")
        self.huawei_action = QtWidgets.QAction(MainWindow)
        self.huawei_action.setObjectName("huawei_action")
        self.tplink_action_2 = QtWidgets.QAction(MainWindow)
        self.tplink_action_2.setObjectName("tplink_action_2")
        self.cwe_info = QtWidgets.QAction(MainWindow)
        self.cwe_info.setObjectName("cwe_info")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.OSPFv2_action = QtWidgets.QAction(MainWindow)
        self.OSPFv2_action.setObjectName("OSPFv2_action")
        self.snmp2_action = QtWidgets.QAction(MainWindow)
        self.snmp2_action.setObjectName("snmp2_action")
        self.NDP_action = QtWidgets.QAction(MainWindow)
        self.NDP_action.setObjectName("NDP_action")
        self.NTP_action = QtWidgets.QAction(MainWindow)
        self.NTP_action.setObjectName("NTP_action")
        self.logs_action = QtWidgets.QAction(MainWindow)
        self.logs_action.setObjectName("logs_action")
        self.BGP_4_action = QtWidgets.QAction(MainWindow)
        self.BGP_4_action.setObjectName("BGP_4_action")
        self.RIPv2_action = QtWidgets.QAction(MainWindow)
        self.RIPv2_action.setObjectName("RIPv2_action")
        self.about_action = QtWidgets.QAction(MainWindow)
        self.about_action.setObjectName("about_action")
        self.actiona = QtWidgets.QAction(MainWindow)
        self.actiona.setObjectName("actiona")
        self.actiona_2 = QtWidgets.QAction(MainWindow)
        self.actiona_2.setObjectName("actiona_2")
        self.actionb = QtWidgets.QAction(MainWindow)
        self.actionb.setObjectName("actionb")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.actiona_3 = QtWidgets.QAction(MainWindow)
        self.actiona_3.setObjectName("actiona_3")
        self.protocol_menu.addAction(self.snmp_action)
        self.protocol_menu.addAction(self.ftp_action)
        self.protocol_menu.addAction(self.dns_action)
        self.protocol_menu.addAction(self.http_action)
        self.protocol_menu.addAction(self.other_action)
        self.help_menu.addAction(self.about_action)
        self.menuall.addAction(self.tplink_action)
        self.menuall.addAction(self.dlink_action)
        self.menuall.addAction(self.huawei_action)
        self.menuall.addAction(self.tplink_action_2)
        self.menu_vul.addAction(self.menuall.menuAction())
        self.menu_vul.addAction(self.cwe_info)
        self.menu_vul.addAction(self.action_4)
        self.menu_vul.addAction(self.action_3)
        self.menubar.addAction(self.protocol_menu.menuAction())
        self.menubar.addAction(self.menu_vul.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "渗透报文生成"))
        self.protocol_menu.setTitle(_translate("MainWindow", "协议选择"))
        self.help_menu.setTitle(_translate("MainWindow", "帮助"))
        self.menu_vul.setTitle(_translate("MainWindow", "漏洞知识库"))
        self.menuall.setTitle(_translate("MainWindow", "所有漏洞"))
        self.network_menu.setText(_translate("MainWindow", "网络层"))
        self.trans_menu.setText(_translate("MainWindow", "传输层"))
        self.snmp_action.setText(_translate("MainWindow", "SNMP"))
        self.ftp_action.setText(_translate("MainWindow", "FTP"))
        self.http_action.setText(_translate("MainWindow", "HTTP"))
        self.dns_action.setText(_translate("MainWindow", "DNS"))
        self.other_action.setText(_translate("MainWindow", "other"))
        self.all_action.setText(_translate("MainWindow", "所有漏洞"))
        self.tplink_action.setText(_translate("MainWindow", "tplink漏洞"))
        self.dlink_action.setText(_translate("MainWindow", "dlink漏洞"))
        self.huawei_action.setText(_translate("MainWindow", "huawei漏洞"))
        self.tplink_action_2.setText(_translate("MainWindow", "tenda漏洞"))
        self.cwe_info.setText(_translate("MainWindow", "CWE信息"))
        self.action_3.setText(_translate("MainWindow", "网络设备关联规则"))
        self.action_4.setText(_translate("MainWindow", "漏洞类别关联规则"))
        self.OSPFv2_action.setText(_translate("MainWindow", "OSPFv2"))
        self.snmp2_action.setText(_translate("MainWindow", "snmp"))
        self.NDP_action.setText(_translate("MainWindow", "NDP"))
        self.NTP_action.setText(_translate("MainWindow", "NTP"))
        self.logs_action.setText(_translate("MainWindow", "logs"))
        self.BGP_4_action.setText(_translate("MainWindow", "BGP-4"))
        self.RIPv2_action.setText(_translate("MainWindow", "RIPv2"))
        self.about_action.setText(_translate("MainWindow", "关于"))
        self.actiona.setText(_translate("MainWindow", "a"))
        self.actiona_2.setText(_translate("MainWindow", "插桩"))
        self.actionb.setText(_translate("MainWindow", "渗透报文生成"))
        self.action.setText(_translate("MainWindow", "插桩"))
        self.action_2.setText(_translate("MainWindow", "渗透报文生成"))
        self.actiona_3.setText(_translate("MainWindow", "a"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
